#ifndef READER_DEF_H
#define READER_DEF_H

#define DEV_ADDR 0x00

// 18000-6C Commands
#define TAG_INV 0x01
#define READ_DATA 0x02
#define WRITE_DATA 0x03
#define WRITE_EPC 0x04
#define KILL_TAG 0x05
#define SET_MEMORY_RW_PROTECTION 0x06
#define BLOCK_ERASE 0x07
#define READ_PROTECTION_CONFIG_EPC 0x08
#define READ_PROTECTION_CONFIG 0x09
#define UNLOCK_READ_PROTECTION 0x0a
#define READ_PROTECTION_STATUS_CHECK 0x0b
#define EAS_CONFIG 0x0c
#define EAS_ALERT_DETECTION 0x0d
#define SINGLE_TAG_INV 0x0f
#define WRITE_BLOCKS 0x10
#define OBTAIN_MONZA4QT_PARAMS 0x11
#define MODIFY_MONZA4QT_PARAMS 0x12
#define EXTENDED_READ_DATA_MASK 0x15
#define EXTENDED_WRITE_DATA_MASK 0x16
#define INVENTORY_MEMORY_BUFFER 0x18
#define MIX_INVENTORY 0x19
#define INVENTORY_EPC 0x1a
#define QT_INVENTORY 0x1b

// 18000-6B Commands
#define SINGLE_TAG_INV_6B 0x50
#define MULTIPLE_TAG_INV_6B 0x51
#define READ_DATA_6B 0x52
#define WRITE_DATA_6B 0x53
#define OBTAIN_LOCK_STATUS_6B 0x54
#define BYTE_LOCKING_6B 0x55

// Reader Customized Command
#define OBTAIN_READER_INFO 0x21
#define MODIFY_WORKING_FREQ 0x22
#define MODIFY_READER_ADDR 0x24
#define MODIFY_READER_INV_TIME 0x25
#define MODIFY_SERIAL_BAUD_RATE 0x28
#define MODIFY_RF_POWER 0x2f
#define LED_BUZZER_CONTROL 0x33
#define SETUP_ANTENNA_MULTIPLEXING 0x3f
#define ENABLE_DISABLE_BUZZER 0x40
#define GPIO_CONTROL 0x46
#define OBTAIN_GPIO_STATE 0x47
#define OBTAIN_READER_SERIAL_NUM 0x4c
#define MODIFY_TAG_CUSTOM_FUNC 0x3a
#define ENABLE_ANTENNA_CHECK 0x66
#define MODIFY_COMM_INTERFACE 0x6a
#define MODIFY_LOAD_ANTENNA_RETURN_LOSS_THRESHOLD 0x6e
#define MODIFY_MAX_EPC_TID_LENGTH_CONFIG_MEM_BUFFER 0x70
#define LOAD_MAX_EPC_TID_LENGTH_CONFIG 0x71
#define OBTAIN_DATA_MEMORY_BUFFER 0x72
#define CLEAR_MEMORY_BUFFER 0x73
#define OBTAIN_TOTAL_TAG_AMOUNT_MEM_BUFFER 0x74
#define MODIFY_REAL_TIME_INV_MODE_PARAMS 0x75
#define MODIFY_WORKING_MODE 0x76
#define LOAD_REAL_TIME_INV_MODE_PARAMS 0x77
#define LOAD_MODIFY_HEARTBEAT_PACKET_TIME_BREAK_REAL_TIME_INV 0x78
#define MODIFY_RF_POWER_CONFIG_SEPARATELY_WRITE_OPS 0x79
#define LOAD_RF_POWER_CONFIG_WRITE_OPS 0x7a
#define MODIFY_LOAD_MAX_WRITE_RETRY_TIME_CONFIG 0x7b
#define MODIFY_TAG_CUSTOM_FUNC_PASS 0x7d
#define OBTAIN_TAG_CUSTOM_FUNC_PASS 0x7e
#define LOAD_MODIFY_READER_PROFILE 0x7f
#define SYNCHRONISE_EM4325_TIMESTAMP 0x85
#define OBTAIN_EM4325_TEMP_DATA 0x86
#define OBTAIN_EXTERNAL_DATA_EM4325_SPI 0x87
#define RESET_EM4325_ALERT 0x88
#define MODIFY_LOAD_DRM_CONFIG 0x90
#define MEASURE_ANTENNA_RETURN_LOSS 0x91
#define MEASURE_CURRENT_READER_TEMP 0x92

//RESPONSE STATUS CODES 
#define OPERATION_SUCCEED 0x00
#define INVENTORY_SUCCEED 0x01
#define INVENTORY_TIMEOUT 0x02
#define FURTHER_DATA_WAITING 0x03
#define READER_MEMORY_FULL 0x04
#define ACCESS_PASSWORD_ERROR 0x05
#define TAG_KILLING_FAILED 0x09
#define ALL_ZERO_KILL_PASSWORD_FAIL 0x0A
#define COMMAND_NOT_SUPPORTED 0x0B
#define ALL_ZERO_ACCESS_PASSWORD_FAIL 0x0C
#define READ_PROTECTION_FAILED 0x0D
#define UNLOCK_TAG_FAILED 0x0E
#define WRITE_OPERATION_FAILED 0x10
#define LOCK_OPERATION_FAILED_6B 0x11
#define LOCK_OPERATION_FAILED_ALREADY_LOCKED 0x12
#define STORE_PARAMETER_FAILED 0x13
#define RF_POWER_ADJUST_FAILED 0x14
#define INVENTORY_6B_SUCCEED 0x15
#define INVENTORY_6B_TIMEOUT 0x16
#define FURTHER_DATA_6B_WAITING 0x17
#define READER_MEMORY_6B_FULL 0x18
#define ALL_ZERO_ACCESS_OR_FUNCTION_NOT_SUPPORTED 0x19
#define TAG_CUSTOMISED_COMMAND_FAILED 0x1A
#define STATISTIC_DATA_PACKET 0x26
#define HEARTBEAT_PACKET 0x28
#define ANTENNA_CONNECTION_FAILURE 0xF8
#define COMMAND_EXECUTION_ERROR 0xF9
#define OPERATION_FAILED_POOR_COMMUNICATION 0xFA
#define NO_OPERATABLE_TAGS 0xFB
#define TAG_ERROR_CODE_RETURNED 0xFC
#define COMMAND_LENGTH_ERROR 0xFD
#define ILLEGAL_COMMAND 0xFE
#define PARAMETER_ERROR 0xFF


#endif
